apiVersion: v2
name: k8s-gateway
description: A Helm chart for the k8s_gateway CoreDNS plugin
type: application
version: 3.3.0
appVersion: 1.6.1
maintainers:
  - url: https://github.com/samip5
    name: samip5
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: add podAnnotations support
